'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.WebService1Soap")>  _
    Public Interface WebService1Soap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Listar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Listar() As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Listar", ReplyAction:="*")>  _
        Function ListarAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Buscar(ByVal texto As String, ByVal criterio As String) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Buscar", ReplyAction:="*")>  _
        Function BuscarAsync(ByVal texto As String, ByVal criterio As String) As System.Threading.Tasks.Task(Of System.Data.DataSet)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Eliminar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Eliminar(ByVal codEscuela As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Eliminar", ReplyAction:="*")>  _
        Function EliminarAsync(ByVal codEscuela As String) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Agregar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Agregar(ByVal codEscuela As String, ByVal Escuela As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Agregar", ReplyAction:="*")>  _
        Function AgregarAsync(ByVal codEscuela As String, ByVal Escuela As String) As System.Threading.Tasks.Task(Of String())
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Actualizar", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function Actualizar(ByVal codEscuela As String, ByVal Escuela As String) As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/Actualizar", ReplyAction:="*")>  _
        Function ActualizarAsync(ByVal codEscuela As String, ByVal Escuela As String) As System.Threading.Tasks.Task(Of String())
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface WebService1SoapChannel
        Inherits ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WebService1SoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.WebService1Soap)
        Implements ServiceReference1.WebService1Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Listar() As System.Data.DataSet Implements ServiceReference1.WebService1Soap.Listar
            Return MyBase.Channel.Listar
        End Function
        
        Public Function ListarAsync() As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference1.WebService1Soap.ListarAsync
            Return MyBase.Channel.ListarAsync
        End Function
        
        Public Function Buscar(ByVal texto As String, ByVal criterio As String) As System.Data.DataSet Implements ServiceReference1.WebService1Soap.Buscar
            Return MyBase.Channel.Buscar(texto, criterio)
        End Function
        
        Public Function BuscarAsync(ByVal texto As String, ByVal criterio As String) As System.Threading.Tasks.Task(Of System.Data.DataSet) Implements ServiceReference1.WebService1Soap.BuscarAsync
            Return MyBase.Channel.BuscarAsync(texto, criterio)
        End Function
        
        Public Function Eliminar(ByVal codEscuela As String) As String() Implements ServiceReference1.WebService1Soap.Eliminar
            Return MyBase.Channel.Eliminar(codEscuela)
        End Function
        
        Public Function EliminarAsync(ByVal codEscuela As String) As System.Threading.Tasks.Task(Of String()) Implements ServiceReference1.WebService1Soap.EliminarAsync
            Return MyBase.Channel.EliminarAsync(codEscuela)
        End Function
        
        Public Function Agregar(ByVal codEscuela As String, ByVal Escuela As String) As String() Implements ServiceReference1.WebService1Soap.Agregar
            Return MyBase.Channel.Agregar(codEscuela, Escuela)
        End Function
        
        Public Function AgregarAsync(ByVal codEscuela As String, ByVal Escuela As String) As System.Threading.Tasks.Task(Of String()) Implements ServiceReference1.WebService1Soap.AgregarAsync
            Return MyBase.Channel.AgregarAsync(codEscuela, Escuela)
        End Function
        
        Public Function Actualizar(ByVal codEscuela As String, ByVal Escuela As String) As String() Implements ServiceReference1.WebService1Soap.Actualizar
            Return MyBase.Channel.Actualizar(codEscuela, Escuela)
        End Function
        
        Public Function ActualizarAsync(ByVal codEscuela As String, ByVal Escuela As String) As System.Threading.Tasks.Task(Of String()) Implements ServiceReference1.WebService1Soap.ActualizarAsync
            Return MyBase.Channel.ActualizarAsync(codEscuela, Escuela)
        End Function
    End Class
End Namespace
